### ISSUE TITLE
Suggestion - shorten first example gif

### ISSUE THREAD

**Issue by autoreleasefool** [rishabhbhatia/react-native-swipeview#1]
The first gif in the README takes about 30 seconds before it shows the actual functionality this component provides. Shorten it immensely. Have a populated to do list, and show the swiping action to complete or remove immediately. Then consider adding one item, or showing the completed items list. Then let the gif loop. Someone interested in using this component is not interested in your to do list app.

**Comment by rishabhbhatia** [comment]
@josephroque Feedback well received Joseph, the gif is shortened.
