### ISSUE TITLE
This doesn’t have a native feel :/

### ISSUE THREAD

**Issue by oferRounds** [rishabhbhatia/react-native-swipeview#2]

**Comment by rishabhbhatia** [comment]
Absolutely, there's always room for improvement. Totally open for PR and suggestions. @oferRounds

**Comment by oferRounds** [comment]
Not sure, but I think the idea — at least in iOS — is to "hook" to the Native api, which supports cell’s swipe.

**Comment by rishabhbhatia** [comment]
Definitely appreciate the idea, this however is a Pure JS solution. I'm open for a PR if you can implement, else totally something I'd explore in near future.
Let's take this talk off issues, I'm available for conversations at rishabh.bhatia08@gmail.com.

**Comment by oferRounds** [comment]
@rishabhbhatia got you, cool! thanks for your reply! :)
